@startuml
' 在开头就定义是必须的
skinparam class {
' 背景颜色
BackgroundColor PaleGreen
' 箭头颜色
ArrowColor SeaGreen
' 包边颜色
BorderColor SpringGreen
}
' spot颜色
skinparam stereotypeCBackgroundColor YellowGreen

Class01 "1" *-- "many" Class02 : contains
Class03 o-- Class04 : aggregation
@enduml

@startuml
' skinned stereotypes 可单独指定
skinparam class {
BackgroundColor PaleGreen
ArrowColor SeaGreen
BorderColor SpringGreen
BackgroundColor<<Foo>> Wheat
BorderColor<<Foo>> Tomato
}

skinparam stereotypeCBackgroundColor YellowGreen
skinparam stereotypeCBackgroundColor<<Foo>> DimGray

class Class01 <<Foo>>
class Class03 <<Foo>>

Class01 "1" *-- "many" Class02 : contains
Class03 o-- Class04 : aggregation
@enduml

